export const TESTERS: any[] = [
    {
        "cid": "5c00fcf338b43ce91539d5c5",
        "code": "consectetur",
        "titleName": "นางสาว",
        "fName": "Candy",
        "lName": "Joyce",
        "age": 26,
        "gender": "female",
        "company": "ZOLAREX",
        "email": "candyjoyce@zolarex.com",
        "phone": 887659323
    },
    {
        "cid": "5c00fcf3aa7cabb561cb8549",
        "code": "commodo",
        "titleName": "นาย",
        "fName": "Hilary",
        "lName": "Chase",
        "age": 26,
        "gender": "female",
        "company": "INVENTURE",
        "email": "hilarychase@inventure.com",
        "phone": 891440434
    },
    {
        "cid": "5c00fcf3db79cfa8f9a55bd6",
        "code": "esse",
        "titleName": "นาย",
        "fName": "Alberta",
        "lName": "Kent",
        "age": 30,
        "gender": "female",
        "company": "PLASTO",
        "email": "albertakent@plasto.com",
        "phone": 897841434
    },
    {
        "cid": "5c00fcf3b6fe2415c4a454be",
        "code": "tempor",
        "titleName": "นางสาว",
        "fName": "Franklin",
        "lName": "Wooten",
        "age": 36,
        "gender": "male",
        "company": "IMKAN",
        "email": "franklinwooten@imkan.com",
        "phone": 891741525
    },
    {
        "cid": "5c00fcf32fcb2d9afdb3ac00",
        "code": "ipsum",
        "titleName": "นาย",
        "fName": "Pam",
        "lName": "Hanson",
        "age": 29,
        "gender": "female",
        "company": "INFOTRIPS",
        "email": "pamhanson@infotrips.com",
        "phone": 887653323
    },
    {
        "cid": "5c00fcf3ebef4bd6529069ee",
        "code": "minim",
        "titleName": "นาง",
        "fName": "Cherry",
        "lName": "Figueroa",
        "age": 21,
        "gender": "female",
        "company": "ENVIRE",
        "email": "cherryfigueroa@envire.com",
        "phone": 890156239
    },
    {
        "cid": "5c00fcf36295b34a3ed27360",
        "code": "adipisicing",
        "titleName": "นางสาว",
        "fName": "Hall",
        "lName": "Morse",
        "age": 35,
        "gender": "male",
        "company": "KROG",
        "email": "hallmorse@krog.com",
        "phone": 888656033
    },
    {
        "cid": "5c00fcf351e76621fd85e39e",
        "code": "mollit",
        "titleName": "นาย",
        "fName": "Sheree",
        "lName": "Navarro",
        "age": 25,
        "gender": "female",
        "company": "STROZEN",
        "email": "shereenavarro@strozen.com",
        "phone": 897950829
    },
    {
        "cid": "5c00fcf394c068108a214c3c",
        "code": "irure",
        "titleName": "นาย",
        "fName": "Sharron",
        "lName": "Macdonald",
        "age": 37,
        "gender": "female",
        "company": "TURNLING",
        "email": "sharronmacdonald@turnling.com",
        "phone": 887146327
    }
]