export const CANDIDATES: any[] = [
  {
    "cid": "5c00f39921234527de7aaee5",
    "titleName": "นาย",
    "fName": "Mari",
    "lName": "Lester",
    "age": 23,
    "gender": "female",
    "grade": "ม.6",
    "educate": "GEEKULAR",
    "email": "marilester@geekular.com",
    "phone": 883644723,
    "addr1": "id enim",
    "addr2": "tempor",
    "tambon": "Beason",
    "amphur": "Colorado",
    "province": "Qatar",
    "zipcode": 99635,
    "regisDate": "03/12/2018"
  },
  {
    "cid": "5c00f399507f28830220deec",
    "titleName": "นาง",
    "fName": "Claudine",
    "lName": "Wells",
    "age": 24,
    "gender": "female",
    "grade": "ปวช",
    "educate": "ACCIDENCY",
    "email": "claudinewells@accidency.com",
    "phone": 881452720,
    "addr1": "quis dolore",
    "addr2": "mollit",
    "tambon": "Vallonia",
    "amphur": "Georgia",
    "province": "Romania",
    "zipcode": 98805,
    "regisDate": "21/12/2018"
  },
  {
    "cid": "5c00f399bb0860e1f2d017de",
    "titleName": "นาง",
    "fName": "Marsh",
    "lName": "Frederick",
    "age": 22,
    "gender": "male",
    "grade": "ปวส",
    "educate": "SEALOUD",
    "email": "marshfrederick@sealoud.com",
    "phone": 892943726,
    "addr1": "enim dolore",
    "addr2": "veniam",
    "tambon": "Iberia",
    "amphur": "New Hampshire",
    "province": "Bulgaria",
    "zipcode": 98975,
    "regisDate": "07/12/2018"
  },
  {
    "cid": "5c00f3997e3b8d35fc31da70",
    "titleName": "นาง",
    "fName": "Vincent",
    "lName": "Higgins",
    "age": 37,
    "gender": "male",
    "grade": "ป.ตรี",
    "educate": "APPLIDEC",
    "email": "vincenthiggins@applidec.com",
    "phone": 890940934,
    "addr1": "in eu",
    "addr2": "elit",
    "tambon": "Leming",
    "amphur": "Montana",
    "province": "Guinea",
    "zipcode": 98455,
    "regisDate": "29/12/2018"
  },
  {
    "cid": "5c00f3995f5dde8991fd654d",
    "titleName": "นาย",
    "fName": "Kim",
    "lName": "Steele",
    "age": 24,
    "gender": "female",
    "grade": "ม.6",
    "educate": "FARMAGE",
    "email": "kimsteele@farmage.com",
    "phone": 893452537,
    "addr1": "est fugiat",
    "addr2": "nostrud",
    "tambon": "Tecolotito",
    "amphur": "Arizona",
    "province": "Brunei Darussalam",
    "zipcode": 99924,
    "regisDate": "11/12/2018"
  },
  {
    "cid": "5c00f3993e9252b9b9a3dcad",
    "titleName": "นางสาว",
    "fName": "Roseann",
    "lName": "Le",
    "age": 23,
    "gender": "female",
    "grade": "ม.6",
    "educate": "RUGSTARS",
    "email": "roseannle@rugstars.com",
    "phone": 880549434,
    "addr1": "irure aliqua",
    "addr2": "ut",
    "tambon": "Itmann",
    "amphur": "Wisconsin",
    "province": "Sudan",
    "zipcode": 99594,
    "regisDate": "27/12/2018"
  },
  {
    "cid": "5c00f399d232c0c205c9dcf6",
    "titleName": "นาง",
    "fName": "Mcneil",
    "lName": "Dixon",
    "age": 25,
    "gender": "male",
    "grade": "ม.6",
    "educate": "GROK",
    "email": "mcneildixon@grok.com",
    "phone": 882459831,
    "addr1": "esse reprehenderit",
    "addr2": "laboris",
    "tambon": "Sexton",
    "amphur": "Ohio",
    "province": "Bahamas",
    "zipcode": 98345,
    "regisDate": "20/12/2018"
  },
  {
    "cid": "5c00f3994a5b2130937a8050",
    "titleName": "นาง",
    "fName": "Verna",
    "lName": "Long",
    "age": 40,
    "gender": "female",
    "grade": "ปวส",
    "educate": "TECHADE",
    "email": "vernalong@techade.com",
    "phone": 889355540,
    "addr1": "est quis",
    "addr2": "nulla",
    "tambon": "Leeper",
    "amphur": "Puerto Rico",
    "province": "Tonga",
    "zipcode": 99255,
    "regisDate": "08/12/2018"
  }
]